SRCS  =
SRCS += lighteffects/LightEffectServices.cpp


LIB   = services.a

include /Volumes/XBMC/mrmc-private/Makefile.include
-include $(patsubst %.cpp,%.P,$(patsubst %.c,%.P,$(patsubst %.S,,$(SRCS))))
