SRCS  = DBManagerRed.cpp
SRCS += GUIDialogRed.cpp
SRCS += GUIDialogRedAbout.cpp
SRCS += MediaManagerRed.cpp
SRCS += PlayBackManagerRed.cpp
SRCS += PlayerManagerRed.cpp
SRCS += PythonBindingsRed.cpp
SRCS += ReportManagerRed.cpp
SRCS += UpdateManagerRed.cpp
SRCS += UtilitiesRed.cpp

LIB   = red.a

include ../../Makefile.include
-include $(patsubst %.cpp,%.P,$(patsubst %.c,%.P,$(SRCS)))
